name: main
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^1.1.0
  url_launcher: ^6.1.11
  flutter_otp_text_field: ^1.1.0+2
  buttons_tabbar: ^1.3.7+1
  info_popup: ^3.0.5

  # Flutter multiplatform navigation sidebar / side navigationbar / drawer widget
  sidebarx: ^0.16.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  awesome_bottom_bar: ^1.2.3
  flutter_svg: ^1.1.5
  google_fonts: ^5.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^10.5.0
  otp_text_field: ^1.1.3
  timelines: ^0.1.0
  image_picker: ^1.0.1
  galleryimage: ^2.0.1
  file_picker: ^4.0.0

  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.4.0
  google_places_flutter: ^2.0.6
  iconify_flutter: ^0.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1
  get: ^4.6.5
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  sleek_circular_slider: ^2.0.1
  dropdown_textfield: ^1.0.8
  booking_calendar: ^1.1.9
  multi_validator: ^1.0.1
  form_field_validator: ^1.0.1
  flutter_dotenv: ^5.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
        - .env
        - assets/
        - assets/galleFort.png
        - assets/unawatuna.png
        - assets/jungleBeach.png
        - assets/galle fort hotel.png
        - assets/le grand.png
        - assets/blue beach.png
        - assets/mango house.png
        - assets/sl railways.png
        - assets/bus seat.png
        - assets/pick me.png
        - assets/uber.png
        - assets/eseat.png
        - assets/bus ticket.png
        - assets/bookaway.png
        - assets/dialus.png
        - assets/weather.png
        - assets/yala.png
        - assets/nuwara eliya.jpg
        - assets/unawatuna beach.jpg
        - assets/colombo.jpg
        - assets/galle public.png
        - assets/logo-travelmate.png
        - assets/post.png
        - assets/profile.png
        - assets/tourPlan.jpg
        - assets/2.jpeg
        - assets/download.jpeg
        - assets/3.jpeg
        - assets/4.jpeg
        - assets/5.jpeg
        - assets/6.jpg
        - assets/7.jpeg
        - assets/8.jpeg
        - assets/9.jpeg
        - assets/10.jpg
        - assets/11.jpg
        - assets/12.jpeg
        - assets/13.jpg
        - assets/cover.jpeg
        - assets/Message.jpg
        - assets/surfing.jpg
        - assets/hiking.jpeg
        - assets/camping.png
        - assets/snorkiln.png
        - assets/profile_pic.jpeg
        - assets/beach.jpg
        - assets/beach2.jpeg
        - assets/jungle.jpg
        - assets/tiger.jpeg
        - assets/river.jpg
        - assets/sigiriya.jpg
        - assets/travellers.jpg
        - assets/elephant.jpg
        - assets/fam.jpg
        - assets/ella.jpg
        - assets/img/
        - assets/svg/
        - assets/galleFort.png
        - assets/unawatuna.png
        - assets/jungleBeach.png
        - assets/galle fort hotel.png
        - assets/le grand.png
        - assets/blue beach.png
        - assets/mango house.png
        - assets/sl railways.png
        - assets/bus seat.png
        - assets/pick me.png
        - assets/uber.png
        - assets/eseat.png
        - assets/bus ticket.png
        - assets/bookaway.png
        - assets/dialus.png
        - assets/weather.png
        - assets/yala.png
        - assets/nuwara eliya.jpg
        - assets/unawatuna beach.jpg
        - assets/colombo.jpg
        - assets/galle public.png
        - assets/logo-travelmate.png
        - assets/post.png
        - assets/profile.png
        - assets/tourPlan.jpg
        - assets/gregory lake.png
        - assets/jungle beach.jpg
        - assets/map_style.txt
        - assets/icons.png
        - assets/icons/
        - assets/weather/
        - assets/gregory.jpg
        - assets/gregoryLake.jpg
        - assets/cycling.jpg
        - assets/safari.jpg
        - assets/blog.png

        - assets/man.jpg
        - assets/woman.jpeg
        - assets/woman2.jpg
        - assets/upload.png
        - assets/beachpost.jpg
        - assets/post2.jpeg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Qwingley
        fonts:
          - asset: fonts/Qwigley-Regular.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

