name: main
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.11
  flutter_otp_text_field: ^1.1.0+2
  buttons_tabbar: ^1.3.7+1
  info_popup: ^3.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  sliding_up_panel: ^2.0.0+1
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
        - assets/galleFort.png
        - assets/unawatuna.png
        - assets/jungleBeach.png
        - assets/galle fort hotel.png
        - assets/le grand.png
        - assets/blue beach.png
        - assets/mango house.png
        - assets/sl railways.png
        - assets/bus seat.png
        - assets/pick me.png
        - assets/uber.png
        - assets/eseat.png
        - assets/bus ticket.png
        - assets/bookaway.png
        - assets/dialus.png
        - assets/weather.png
        - assets/yala.png
        - assets/nuwara eliya.jpg
        - assets/unawatuna beach.jpg
        - assets/colombo.jpg
        - assets/galle public.png
        - assets/logo-travelmate.png
        - assets/post.png
        - assets/profile.png
        - assets/tourPlan.jpg
        - assets/gregory lake.png
        - assets/jungle beach.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

